### ISSUE TITLE
TODO - Review

### ISSUE THREAD

**Issue by tlorentzen** [tlorentzen/P3#114]
# Generelt
- [x] Alle lister har forskellige række-højder (Somewhat fixed. Problemet med users er department dropdown og textboxes for description og domain) (Fly)
- [x] Department menu er lidt spøjs (Niels)
- [x] Config-fil til database config
- [x] Mindre fokus på ID af ting, mere fokus på navn og identifier
- [x] Den del af programmet, som brugeren er i (assets, tags, log, ...) skal være markeret i menu baren i venstre side (Niels)
- [x] Ens styles i hele appen
- [x] Tab giver ArgumentNullException når der trykkes for mange gange og holder sig ikke indenfor popup vindue (TGL)
- [x] Ingen new repositories
- [x] Slet alle Console.WriteLines (Kun exceptions tilbage, primært i repositories) Alle exceptions skal logges i loggen (Niels)
- [x] Tag "piller" skal vise hvor de kommer fra i forhold til parent. Label skal have 'ParentLabel:' foran sig (Niels)
- [x] Man kan ikke redigere i fields (fx navn) (Niels)
- [x] Field er altid ikke custom (Niels)
- [x] Default sortering på alle lister (TGL)
- [x] Default limit på alle lister (TGL)
- [x] ISearchableRepository skal væk...
- [x] Fjern navn på 'users'-tabel (TGL)
- [x] Comments benytter ikke user_id, men username og er dermed ikke unikt. (TGL)
- [x] Tests køre ikke
- [x] Skrive nye tests til ny kode
- [x] Det er ikke muligt at tilføje departments når databasen er tom. (Fly)
- [x] Double reload på db på asset - department skift
- [x] Shift + Tab i tag suggestion listerne i AssetList og AssetEditor skal decrease tabIndexen i den tilhørende ViewModel (Niels)

## Home
- [x] Skal det tilføjes mere?
- [x] Limit på comments de seneste 100? (TGL)
- [x] Redesign af commentarerne (Niels)

## Assets 
- [x] Forholdsvis lang loadtime
- [x] Parent tag duplicates across departments for asset search and asset tagging (Niels)

### List
- [x] Export/Print exporter forkert format (Ender linjer med comma)
- [x] Vælg alle checkbox (List header) (Fly)
- [x] Strict search virker ikke
- [x] Skift datoformat ved export
- [x] søjle/column bredde (sæt min bredde) (Fly)
- [x] Række ikoner skal helt til højre
- [x] Man kan ikke sortere på kolonne headers (Kunne man i det gamle)
- [x] Remove multiple virker kun til 2 assets 👎 (Fly)
- [x] Strict search virker ikke, hvis parent tagget er på (TGL)
- [x] Trashcan virker ikke (Fly)
- [x] Notifikation, når bruger prøver at tagge noget på søgningen, der ikke er et tag (Fly)
- [x] Remove selected med "remove button" virker ikke helt optimalt (Fly)
- [x] Tilføj assetnes id

### Edit
- [x] Field: remove field kryds halt skjult (Fly)
- [x] Field: Required stjerne er for tæt på linjen, muligvis bør den flyttes til højre for feltet. (Fly)
- [x] Field: Add field popup skal redesignes (Fly)
- [x] Field: Fieldtype "checkbox" default værdi har "This is a checkbox"? Bør nok fjernes
- [x] Field: Default checkbox svæver... (Fly)
- [x] Slet knap i view (Fly)
- [x] Fungere hidden-fields?
- [x] Felter har andet style end resten af applikationen. (Fly)
- [x] Field: Datefield har en default today, som ikke virker.
- [x] Det er ikke muligt at tagge tags på assets (Alexander)
- [x] Allerede tilføjede tags vises ikke ved edit
- [x] Validation (Husk dette også skal tilføjes til field edit/create)  
- [x] Custom field bliver ikke gemt
- [x] Tilføj tags er ikke intuitiv ift dropdown (Niels)
- [x] Tags er wobbly
- [x] SQL syntax error når "Save copy" (TGL)
- [x] Mangler check for all department (Fly)
- [x] Required field behøves ikke at være fyldt ved "save copy" (Fly)
- [x] Tag-piller under tagging og under fields er forskellige, fonten følger ikke med. (Niels)
- [x] Det er ikke muligt at smide tags på assets og felterne kommer ikke frem.
- [x] Numberfields kan indeholder alle typer tegn, og ikke kun tal. 
- [x] Notifikation, når bruger prøver at tagge noget på søgningen, der ikke er et tag (Fly)
- [x] Skal hidden fields være lidt mindre synlige, på nuværende tidspunkt er har en meget lille "Hidden fields", men felter under ligner de aktive? (Fly)
- [x] Hvis man er i "All departments" og redigere et asset så kan man ikke gemme, uden at skifte department. (TGL)
- [x] Fjern edit icon på fields fra tags. (Niels)
- [x] Assets nedarver ikke parent-tags fields, før efter save, desuden er feltet ikke forbundet til noget når den så gør. (Niels)
- [x] Remove asset virker ikke
- [x] Double tagging skal ikke være en ting (Alexander)
- [x] AssetRepository prøver at lave en forbindelse mellem et tag og et asset, der allerede eksisterer og får ikke oprettet nogen forbindelser (Alexander)
- [x] Double tagging parent (Fly) (maaaaaayyyybe TGL)
- [x] Implement tabIndex for tagging feltet (Niels)
- [x] Tab burde indsætte tagget fra suggestions, svarende til tabIndex (Niels)
- [x] Enter tilføjer tag eller går ind i parent (Niels)
- [x] Notifikation om ikke eksisterende tag (Fly)
- [x] Fields bliver hidden, hvis tags bliver fjernet fra systemet og assetet bliver redigeret igen. De skulle blive custom, hvis de indeholder en værdi, eller fjernes, hvis de er (Alexander)
- [x] Fields er FUCKED! (Alexander)
- [x] Fields er MEGA store!
- [x] Tag feltet skal give suggestions så snart feltet er i focus (Niels)

### View
- [x] Tilføj delete i view (husk notifikation) (Fly)
- [x] Margin på tabs-view (10) (Fly)
- [x] Margin på indhold i tabs (10) (Fly)
- [x] Notifikation på comment slet
- [x] Fjern 'Name' fra første søjle (Fly)
- [x] Tilføj ID efter navn øverst på siden (Fly)
- [x] Comment textarea følg skærmstørrelse (fuld bredde sammen med knappen)
- [x] Comment textarea tilføj max højde
- [x] Mangler der noget i loggen?
- [x] Double click på log entry for appen til at crashe.
- [x] Log skal passe til det enkelte asset
- [x] Field checkbox vises ikke som checkbox (0 eller True i stedet)
- [x] Viser alle tags, skal ikke vise parents with children. (Benyt TagHelper) (Fly)
- [x] Tag-piller under tagging og under fields er forskellige, fonten følger ikke med.
- [x] AssetControlleren overlever fra editoren og derfor overlever ændringer fra editoren, selvom der blev trykket cancel (Niels)

### List
- [x] Double click i rammen ikke på et tag for vores app til at crashe (Fly)
- [x] Tag med ID: 1 må ikke kunne slettes (bruger/users) (Ane)
- [x] Man kan ikke lave et nyt tag (fieldcontainer er null)
- [x] Search virker ikke (Thomas)
- [x] Man kan slette tags, men det crasher efterfølgende. (Niels)
- [x] Sletning af parent-tag? (Fly)
- [x] Man kan ikke fjerne et parent tag, hvis man er i tag mode og under the parent tag i søgefeltet. Også selvom alle dets børn er fjernet. (Niels)
- [x] Når man tilføjet/fjerner et tag, opdateres listen ikke (Ane)
- [x] Remove tag reloader ikke tree-view (Fly)
- [x] Remove tag prompt viser ikke navnet på tagget (Fly)

### Edit
- [x] Cancel går ikke tilbage (Fly)
- [x] Save virker ikke crash! (Fly)
- [x] Man kan ikke lave et nyt tag (Niels)
- [x] Der bliver ikke hentet parent color (Niels)
- [x] Der bliver ikke hentet department fra parent hvis denne vælges, men der bruges den nuværende (Niels)
- [x] Color changes with parent, if color is same as old parent (Niels)
- [x] Rename 'DepartmentComboEnabled' and 'ParentComboEnabled' to 'DepartmentSelectionEnabled' and 'ParentSelectionEnabled' (Niels)
- [x] User TAG #1 skal ikke kunne ændre department, feltet skal disables. (TGL)
- [x] Skal User TAG #1 kunne have fields? (NEJ! mener Fly)
- [x] Håndter setting parent tag of parent (Niels)
- [x] Child tags skal nedarve parent tagets fields
- [x] Luk-knappen i add field har forkert font. (Niels)
- [x] Numberfields kan indeholder alle typer tegn, og ikke kun tal. 
- [x] Listen af parents er ikke limited til departments. (TGL)
- [x] Bacon department er fuucked
- [x] Parent tags på asset (Niels)
- [x] Vis parent tag fields på child tags (Alexander)
- [x] Valg af parent tag for et nyt child tag giver null reference exception
- [x] Adding a tag to a department, which already contains a parent tag with the same name crashes the program (Fly)

## Log
- [x] Comment logs bliver ikke hentet ud med asset logs, på asset view page (can løses med et kald til comment databasen og så loggen)
- [x] 'Save copy' bliver ikke logget korrekt
- [x] Update typen virker ikke for tag (Niels)

### List
- [x] Søgning virker ikke (Fly)
- [x] Export/print er forkert format samt forkert dato format (Niels)
- [x] Dobbelt click på log række resultere i crash.
- [x] Navn i stedet for "with id X" (Niels)
- [x] Reference fra comments til deres asset (Niels)
- [x] Filtrerings checkboxe med ‘Create’, Delete’, ‘Update’, ‘Error’, og ‘Other’ (Niels)

### View
- [x] Der eksistere ikke noget view (Fly)

### List
- [x] Margin på listview i top og bund

### Editorne
- [x] Field origin tag skal væk for IsCustom felter (Niels)
- [x] Field design update (Niels)
- [x] Hidden fields 'x' should turn to '+' (Niels)
